### ISSUE TITLE
tooltip texts for instance and model icons

### ISSUE THREAD

**Issue by hannesrichter** [koi-learning/koi-pwa#2]
Icons show the current state of each model and instance in the koi-pwa.
For new users, it could be hard to understand the meaning of each icon.

**Comment by jonau** [comment]
tooltips are not feasible for a mobile application user experience. I suggest to keep the icons without a tooltip and display the same information (icon + textual description) in the details panel of the model/instance.

We can make a differentiation between desktop and mobile UI and display the tooltips in the desktop variant. However, I suggest keeping the UX the same between all devices.

I problem remaining is that the user might not be aware that some of the icons are clickable (delete and finalize) and others are not. We should remove the icons from the toolbar and only display actions here.

I also would display the icons all the time and just draw them in color when active.

**Comment by jonau** [comment]
to clarify the issue. Should we still display the icons in this location. Even if no action is connected to them? Do we display the finalized icon once the user can not click it anymore (since the model/instance is already finalized)?
![image](https://user-images.githubusercontent.com/31611009/99545930-2961e400-29b6-11eb-81ea-0edc4d6eb90a.png)
